load("@buildifier_prebuilt//:rules.bzl", "buildifier", "buildifier_test")
load(
    "@rules_rust//rust:defs.bzl",
    "rust_binary",
    "rust_clippy",
    "rust_library",
    "rust_test",
    "rustfmt_test",
)
load("//:defs.bzl", "ahab")

package(default_visibility = ["//visibility:public"])

exports_files([".rustfmt.toml"])

rust_library(
    name = "ahab_lib",
    srcs = [
        "src/aquery.rs",
        "src/checks.rs",
        "src/cli.rs",
        "src/exceptions.rs",
        "src/glob.rs",
        "src/lib.rs",
        "src/melville.rs",
        "src/param_files.rs",
        "src/reproducibility_spec/library.rs",
        "src/reproducibility_spec/mod.rs",
        "src/reproducibility_spec/per_lang/mod.rs",
        "src/reproducibility_spec/per_lang/rust.rs",
        "src/reproducibility_spec/program_id.rs",
        "src/terminal_color.rs",
    ],
    crate_name = "ahab",
    deps = [
        "//proto:analysis_v2_rs_proto",
        "@crates//:anyhow",
        "@crates//:clap",
        "@crates//:prost",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:similar",
    ],
)

rust_binary(
    name = "ahab",
    srcs = ["src/main.rs"],
    deps = [
        ":ahab_lib",
        "@crates//:anyhow",
        "@crates//:clap",
    ],
)

rust_test(
    name = "ahab_lib_test",
    crate = ":ahab_lib",
    deps = [
        "//proto:analysis_v2_rs_proto",
        "@crates//:anyhow",
        "@crates//:clap",
        "@crates//:prost",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:similar",
    ],
)

rust_clippy(
    name = "clippy",
    testonly = True,
    deps = [
        ":ahab",
        ":ahab_lib",
        ":ahab_lib_test",
    ],
)

rustfmt_test(
    name = "rustfmt_test",
    targets = [
        ":ahab",
        ":ahab_lib",
        ":ahab_lib_test",
    ],
)

alias(
    name = "format",
    actual = "@rules_rust//tools/rustfmt",
)

buildifier_test(
    name = "buildifier_test",
    size = "small",
    exclude_patterns = [
        "./.direnv/*",
        "./.git/*",
    ],
    lint_mode = "warn",
    mode = "diff",
    no_sandbox = True,
    workspace = "//:MODULE.bazel",
)

buildifier(
    name = "buildifier",
    exclude_patterns = [
        "./.direnv/*",
        "./.git/*",
    ],
    lint_mode = "fix",
    mode = "fix",
)

ahab(
    name = "hermeticity",
    label = "//...",
)
