"""Bazel rules for running Ahab, the hermeticity analyzer.
"""

load("@bazel_skylib//lib:shell.bzl", "shell")
load("@bazel_skylib//rules:write_file.bzl", "write_file")

def _ahab_impl(ctx):
    args = []
    for config in ctx.attr.configs:
        args.append("--config=" + config)
    if ctx.attr.shut_up:
        args.append("--shut-up")
    if ctx.attr.no_fail:
        args.append("--no-fail")
    if ctx.attr.label:
        args.append(ctx.attr.label)

    words = [shell.quote(arg) for arg in args]

    # The report is written relative to the workspace root, not to wherever
    # the target happened to be run from. A target declared in a BUILD file
    # should put its output in the same place every time.
    if ctx.attr.write_json:
        words.append(shell.quote("--write-json"))
        words.append(
            '"$BUILD_WORKSPACE_DIRECTORY"/' +
            shell.quote(ctx.attr.write_json),
        )

    # Arguments naming a file the build supplied. These have to be made
    # absolute because they live in the runfiles tree, and Ahab would
    # otherwise resolve them against the current working directory.
    inputs = []

    def add_file_arg(flag, file):
        inputs.append(file)
        words.append(shell.quote(flag))
        words.append('"$RUNFILES"/' + shell.quote(file.short_path))

    if ctx.file.explain_json:
        add_file_arg("--explain-json", ctx.file.explain_json)
    if ctx.file.expect_json:
        add_file_arg("--expect-json", ctx.file.expect_json)
    for spec in ctx.files.repro_specs:
        add_file_arg("--repro-specs", spec)
    for exception in ctx.files.exceptions:
        add_file_arg("--exceptions-json", exception)

    ahab = ctx.executable._ahab

    lines = ['exec "$RUNFILES"/' + shell.quote(ahab.short_path)]
    lines.extend(["  " + word for word in words])
    lines.append('  "$@"')

    guard = ""
    if ctx.attr.write_json:
        guard = """
if [ -z "${BUILD_WORKSPACE_DIRECTORY-}" ]; then
  echo "error: BUILD_WORKSPACE_DIRECTORY is not set; run this target with \\`bazel run\\`" >&2
  exit 1
fi
"""

    launcher = ctx.actions.declare_file(ctx.label.name + ".bash")
    ctx.actions.write(
        output = launcher,
        is_executable = True,
        content = """#!/usr/bin/env bash
# Generated by {label}. DO NOT EDIT.
set -euo pipefail

# Under `bazel run` the working directory is the runfiles tree, so this is
# where everything the build handed us can be found.
RUNFILES="$PWD"
{guard}
{command}
""".format(
            label = str(ctx.label),
            guard = guard,
            command = " \\\n".join(lines),
        ),
    )

    runfiles = ctx.runfiles(files = [ahab] + inputs).merge(
        ctx.attr._ahab[DefaultInfo].default_runfiles,
    )
    return [DefaultInfo(
        files = depset([launcher]),
        runfiles = runfiles,
        executable = launcher,
    )]

_ahab = rule(
    implementation = _ahab_impl,
    doc = "Runs Ahab with a fixed command line. Use the `ahab` macro.",
    attrs = {
        "configs": attr.string_list(
            doc = "`--config=<name>` values to forward to `bazel aquery`.",
        ),
        "label": attr.string(
            doc = "The Bazel label or wildcard to analyze.",
        ),
        "shut_up": attr.bool(
            doc = "Suppress the Moby-Dick quote.",
        ),
        "no_fail": attr.bool(
            doc = "Report violations but exit 0 anyway.",
        ),
        "write_json": attr.string(
            doc = "Path to write the report to, relative to the " +
                  "workspace root.",
        ),
        "explain_json": attr.label(
            allow_single_file = True,
            doc = "A saved report to print instead of analyzing.",
        ),
        "expect_json": attr.label(
            allow_single_file = True,
            doc = "A saved report to compare against.",
        ),
        "repro_specs": attr.label_list(
            allow_files = True,
            doc = "Reproducibility spec files, applied in order.",
        ),
        "exceptions": attr.label_list(
            allow_files = True,
            doc = "Exception files, whose contents are unioned.",
        ),
        "_ahab": attr.label(
            default = Label("//:ahab"),
            executable = True,
            cfg = "target",
        ),
    },
    executable = True,
)

def _generated_json(name, kind, index, document):
    """Write one inline value out as a JSON file, and return its label."""
    target = "{}.{}.{}.json".format(name, kind, index)
    write_file(
        name = target,
        out = target,
        content = [json.encode_indent(document, indent = "  ")],
        tags = ["manual"],
    )
    return ":" + target

def _collect(name, kind, values, wrap):
    """Split a list of inline values and file labels into labels alone.

    Inline values become generated JSON files, spliced back in where they
    were written, so that a list's order is the order Ahab sees—which is
    what `repro_specs` precedence depends on.
    """
    labels = []
    for index, value in enumerate(values):
        if type(value) == "string":
            labels.append(value)
        elif type(value) == "dict":
            labels.append(_generated_json(name, kind, index, wrap(value)))
        else:
            fail("{}: {}[{}]: expected a dict or a label, got {}".format(
                name,
                kind,
                index,
                type(value),
            ))
    return labels

def _exception_labels(name, exceptions):
    return _collect(
        name,
        "exceptions",
        exceptions,
        lambda value: {"exceptions": [value]},
    )

def _repro_spec_labels(name, repro_specs):
    return _collect(
        name,
        "repro_specs",
        repro_specs,
        lambda value: {"programs": value},
    )

def ahab(
        name,
        label = None,
        configs = [],
        shut_up = False,
        no_fail = False,
        write_json = None,
        explain_json = None,
        expect_json = None,
        repro_specs = [],
        exceptions = [],
        **kwargs):
    """Defines a target that runs Ahab over part of this workspace.

    Run it with `bazel run`, not `bazel test`, since Ahab shells out to
    Bazel

    `repro_specs` and `exceptions` each take a list whose elements are
    either a label naming a JSON file or a value written out in the BUILD
    file directly. An inline value is written out to a generated JSON file
    and passed to the analyzer.

    Args:
      name: The target's name.
      label: The Bazel label or wildcard to analyze, e.g. `//...`.
        Required, unless `explain_json` is set.
      configs: `--config=<name>` values forwarded to `bazel aquery`.
      shut_up: Suppress the Moby-Dick quote appended to the report.
      no_fail: Print the report but exit 0 even when there are violations.
      write_json: Where to write the report, relative to the workspace
        root. A plain path rather than a label, because it names a file to
        create rather than one the build knows about.
      explain_json: A label naming a saved report to print, instead of
        analyzing anything.
      expect_json: A label naming a saved report to compare against. The
        target exits non-zero on any difference, which is the intended way
        to run Ahab in CI.
      repro_specs: Reproducibility specs, as inline dicts of
        `{program: entry}` or labels naming JSON files. Applied in the
        order given, later overriding earlier.
      exceptions: Exceptions, as inline dicts or labels naming JSON files.
        Order is irrelevant: exceptions compose by union.
      **kwargs: Passed through to the underlying rule, e.g. `visibility`,
        `tags`.
    """
    if not label and not explain_json:
        fail("{}: needs a `label` to analyze, unless `explain_json` is set".format(name))

    _ahab(
        name = name,
        label = label,
        configs = configs,
        shut_up = shut_up,
        no_fail = no_fail,
        write_json = write_json,
        explain_json = explain_json,
        expect_json = expect_json,
        repro_specs = _repro_spec_labels(name, repro_specs),
        exceptions = _exception_labels(name, exceptions),
        **kwargs
    )

def ahab_explain(name, report, shut_up = False, **kwargs):
    """Defines a target that prints a report Ahab saved earlier.

    Bazel is not consulted and nothing is analyzed, so this is fast and
    works anywhere the file does—which is the point: a report written by a
    `write_json` target on one machine can be read back on another.

    Args:
      name: The target's name.
      report: A label naming a JSON report written by `--write-json`.
      shut_up: Suppress the Moby-Dick quote appended to the report.
      **kwargs: Passed through to the underlying rule.
    """
    ahab(
        name = name,
        explain_json = report,
        shut_up = shut_up,
        **kwargs
    )

def _baseline_path(name, baseline):
    """The workspace-relative path of a label naming a baseline file."""
    label = native.package_relative_label(baseline)
    if label.repo_name:
        fail(("{}: baseline {} is in another repository, so this " +
              "workspace cannot write it").format(name, repr(baseline)))
    if label.package:
        return label.package + "/" + label.name
    return label.name

def ahab_check(
        name,
        label,
        baseline,
        configs = [],
        shut_up = False,
        repro_specs = [],
        exceptions = [],
        **kwargs):
    """Defines a target that fails if the violations have changed.

    The companion to `ahab_update`, which writes the file this compares
    against. Define the two together with the same analysis options, or
    they will disagree about what a clean build looks like.

    Nothing is printed and the exit code is 0 when the violations match the
    baseline exactly, counts included; otherwise a diff goes to stderr and
    the target exits non-zero. That makes it the thing to run in CI—with
    `bazel run`, not `bazel test`, since Ahab shells out to Bazel.

    Args:
      name: The target's name.
      label: The Bazel label or wildcard to analyze, e.g. `//...`.
      baseline: A label naming the checked-in report to compare against.
      configs: `--config=<name>` values forwarded to `bazel aquery`.
      shut_up: Suppress the Moby-Dick quote appended to the report.
      repro_specs: Reproducibility specs; see `ahab`.
      exceptions: Exceptions; see `ahab`.
      **kwargs: Passed through to the underlying rule.
    """
    ahab(
        name = name,
        label = label,
        expect_json = baseline,
        configs = configs,
        shut_up = shut_up,
        repro_specs = repro_specs,
        exceptions = exceptions,
        **kwargs
    )

def ahab_update(
        name,
        label,
        baseline,
        configs = [],
        shut_up = False,
        repro_specs = [],
        exceptions = [],
        **kwargs):
    """Defines a target that rewrites the baseline `ahab_check` compares to.

    Run this to accept the violations a build currently has, then commit
    the result. `baseline` is a label rather than a path so that it is
    literally the same string as the matching `ahab_check`'s, and the file
    is written relative to the workspace root, so it lands in the same
    place whatever directory the command was typed in.

    The target exits 0 even though it has just recorded violations:
    recording is not judging, and a baseline that failed on being written
    could not be scripted after. `ahab_check` is what turns the same
    violations into a failure.

    Args:
      name: The target's name.
      label: The Bazel label or wildcard to analyze, e.g. `//...`.
      baseline: A label naming the report to write. Must be in this
        workspace, since it is a source file to be committed.
      configs: `--config=<name>` values forwarded to `bazel aquery`.
      shut_up: Suppress the Moby-Dick quote appended to the report.
      repro_specs: Reproducibility specs; see `ahab`.
      exceptions: Exceptions; see `ahab`.
      **kwargs: Passed through to the underlying rule.
    """
    ahab(
        name = name,
        label = label,
        write_json = _baseline_path(name, baseline),
        no_fail = True,
        configs = configs,
        shut_up = shut_up,
        repro_specs = repro_specs,
        exceptions = exceptions,
        **kwargs
    )
