use super::super::library::{Entry, always, under_both_names};
use super::super::program_id::ProgramId;

/// A program the `go_sdk` extension downloads and unpacks.
fn go_sdk(path: &str) -> ProgramId {
    ProgramId::extension("rules_go", "go_sdk", path)
}

/// The metadata merger shipped by rules_webtesting.
fn metadata_merger(platform: &str) -> ProgramId {
    let extension = if platform == "windows_x64" {
        ".exe"
    } else {
        ""
    };
    ProgramId::module(
        "rules_webtesting",
        &format!("go/metadata/main/main_{platform}{extension}"),
    )
}

/// One of Gazelle's own generators, under both names it answers to.
fn gazelle_generator(path: &str) -> Vec<(ProgramId, Entry)> {
    under_both_names("gazelle", path, Entry::Spec(always()))
}

/// Everything Ahab knows about Go builds, in source order.
pub(in crate::reproducibility_spec) fn entries() -> Vec<(ProgramId, Entry)>
{
    vec![
        // One helper built from the SDK stands behind nearly every Go
        // action, told what to do by a subcommand: `compilepkg`, `link`,
        // `gentestmain`. Arguments are workspace-relative, rules_go trims
        // paths on the way to the compiler, and the linker gets
        // `-buildid=redacted` rather than embedding one of its own.
        //
        // `link` does hand off to a C linker and archiver named
        // absolutely—`-extld /usr/bin/gcc`. Not modelled here: those paths
        // are already in the action for the absolute path check to find,
        // and restating it would report the same machine twice. Same call
        // as for `rustc`.
        (go_sdk("builder_reset/builder"), Entry::Spec(always())),
        // Not a plain wrapper: it runs the protoc named by `-protoc` with
        // the plugin named by `-plugin`, so `Wraps` would answer for protoc
        // alone and drop the plugin. A spec of its own holds because the
        // driver adds nothing—no clock, no environment, no randomness, and
        // the only thing it asks the machine is `runtime.GOOS`.
        (
            ProgramId::module(
                "rules_go",
                "go/tools/builders/go-protoc/go-protoc-bin",
            ),
            Entry::Spec(always()),
        ),
    ]
    .into_iter()
    // Merges the JSON files named on its command line, in order. The four
    // names are one program: rules_webtesting packages every platform's
    // binary in a release.
    .chain(
        ["linux_x64", "darwin_x64", "darwin_arm64", "windows_x64"].map(
            |platform| (metadata_merger(platform), Entry::Spec(always())),
        ),
    )
    // Building Gazelle runs three generators of its own, each turning a
    // file the build handed it—a CSV of proto imports, the SDK's package
    // list—into a Go source file. Here because the alternative is that
    // everyone who uses Gazelle writes the same three specs.
    .chain(gazelle_generator(
        "language/proto/gen/gen_known_imports_/gen_known_imports",
    ))
    .chain(gazelle_generator(
        "language/go/gen_std_package_list/gen_std_package_list_\
         /gen_std_package_list",
    ))
    .chain(gazelle_generator(
        "language/go/platform_info_generator/platform_info_generator_\
         /platform_info_generator",
    ))
    // The yacc of the Go world, reached through Gazelle's `go_deps`. It
    // reads no clock and no environment, and the single map it keeps is
    // only indexed, never ranged over—which is where a Go program of this
    // shape would otherwise pick up randomized iteration order.
    //
    // It does write `// Code generated by goyacc <its own argv>` into the
    // header, so the output contains the output path. That path is
    // workspace-relative and stated by the action.
    //
    // Identified by the extension rather than the Go module, whose
    // repository name is unstable: two modules shipping `cmd/goyacc` would
    // be one program here.
    .chain([(
        ProgramId::extension(
            "gazelle",
            "go_deps",
            "cmd/goyacc/goyacc_/goyacc",
        ),
        Entry::Spec(always()),
    )])
    .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::reproducibility_spec::Conformance;
    use crate::reproducibility_spec::library::Library;
    use crate::reproducibility_spec::per_lang::testing;

    /// A program inside Gazelle, which declares itself as the module
    /// `gazelle` however its dependents spell the repository.
    fn gazelle(path: &str) -> ProgramId {
        ProgramId::module("gazelle", path)
    }

    /// The head of a `compilepkg` command line as rules_go writes it.
    fn compilepkg() -> Vec<&'static str> {
        vec![
            "compilepkg",
            "-sdk",
            "external/rules_go++go_sdk+main___download_0",
            "-goroot",
            "bazel-out/k8-fastbuild/bin/external/rules_go+/stdlib_",
            "-installsuffix",
            "linux_amd64",
            "-src",
            "language/go/gen_std_package_list/gen_std_package_list.go",
            "-importpath",
            "github.com/bazelbuild/bazel-gazelle/language/go",
            "-gcflags",
            "",
        ]
    }

    /// A `link` command line, including the external linker rules_go names
    /// after the separator.
    fn link() -> Vec<&'static str> {
        vec![
            "link",
            "-sdk",
            "external/rules_go++go_sdk+main___download_0",
            "-main",
            "bazel-out/k8-fastbuild/bin/language/go/thing.a",
            "--",
            "-extar",
            "/usr/bin/ar",
            "-extld",
            "/usr/bin/gcc",
            "-buildid=redacted",
        ]
    }

    fn assess(args: Vec<&str>) -> Conformance {
        testing::assess(go_sdk("builder_reset/builder"), args)
    }

    #[test]
    fn the_builder_is_reproducible_whichever_subcommand_it_is_given() {
        assert_eq!(assess(compilepkg()), Conformance::Reproducible);
        assert_eq!(assess(link()), Conformance::Reproducible);
        assert_eq!(
            assess(vec!["gentestmain", "-pkgname", "language/go"]),
            Conformance::Reproducible,
        );
    }

    #[test]
    fn web_test_metadata_merging_is_reproducible_on_every_platform() {
        for platform in
            ["linux_x64", "darwin_x64", "darwin_arm64", "windows_x64"]
        {
            assert_eq!(
                testing::assess(
                    metadata_merger(platform),
                    vec![
                        "--output",
                        "bazel-out/k8-fastbuild/bin/test.gen.json",
                        "browser.gen.json",
                        "test.tmp.json",
                    ],
                ),
                Conformance::Reproducible,
                "{platform}",
            );
        }
    }

    #[test]
    fn the_external_linker_is_left_to_the_other_checks() {
        assert!(link().contains(&"/usr/bin/gcc"));
        assert_eq!(assess(link()), Conformance::Reproducible);
    }

    const STD_PACKAGE_LIST: &str = "language/go/gen_std_package_list\
         /gen_std_package_list_/gen_std_package_list";

    #[test]
    fn gazelles_generators_answer_to_both_of_their_names() {
        for path in [
            "language/proto/gen/gen_known_imports_/gen_known_imports",
            STD_PACKAGE_LIST,
            "language/go/platform_info_generator\
             /platform_info_generator_/platform_info_generator",
        ] {
            let from_module =
                Library::builtin().resolve(gazelle(path), vec![]);
            assert!(from_module.spec.is_some(), "{path} from the module");

            let from_main =
                Library::builtin().resolve(ProgramId::main(path), vec![]);
            let (_, spec) =
                from_main.spec.clone().expect("a spec in the main module");
            assert_eq!(from_main.synonym(), Some(&gazelle(path)), "{path}");
            assert_eq!(
                spec.assess(from_main.args),
                Conformance::Reproducible,
                "{path}",
            );
        }
    }

    #[test]
    fn the_builder_is_named_by_the_extension_that_downloads_it() {
        let resolution = Library::builtin()
            .resolve(go_sdk("builder_reset/builder"), vec!["compilepkg"]);
        assert!(resolution.spec.is_some());
        let elsewhere = Library::builtin().resolve(
            ProgramId::module("rules_go", "builder_reset/builder"),
            vec!["compilepkg"],
        );
        assert!(elsewhere.spec.is_none());
    }

    #[test]
    fn generating_go_from_protos_is_vouched_for() {
        assert_eq!(
            testing::assess(
                ProgramId::module(
                    "rules_go",
                    "go/tools/builders/go-protoc/go-protoc-bin",
                ),
                vec![
                    "-protoc",
                    "external/protobuf+/protoc",
                    "-importpath",
                    "github.com/bazelbuild/buildtools/api_proto",
                    "-plugin",
                    "external/rules_go+/proto/go_proto_reset_plugin_\
                     /protoc-gen-go",
                    "-descriptor_set",
                    "api_proto/api_proto-descriptor-set.proto.bin",
                    "api_proto/api.proto",
                ],
            ),
            Conformance::Reproducible,
        );
    }

    #[test]
    fn the_parser_generator_is_vouched_for() {
        assert_eq!(
            testing::assess(
                ProgramId::extension(
                    "gazelle",
                    "go_deps",
                    "cmd/goyacc/goyacc_/goyacc",
                ),
                vec!["-o", "bin/build/parse.y.baz.go", "build/parse.y"],
            ),
            Conformance::Reproducible,
        );
    }
}
